branches:
  only:
    - master

image: Visual Studio 2015

environment:
  matrix:
    - CONFIGURATION: Release
      GENERATOR: Visual Studio 14 2015
      MAINEXE: mrswatson.exe
      TESTEXE: mrswatsontest.exe
    - CONFIGURATION: Release
      GENERATOR: Visual Studio 14 2015 Win64
      MAINEXE: mrswatson64.exe
      TESTEXE: mrswatsontest64.exe

install:
  - git submodule update --init --recursive

build_script:
  - if exist build (rd /s /q build)
  - mkdir build
  - cd build
  - cmake -D VERBOSE=ON -D CMAKE_BUILD_TYPE=%CONFIGURATION% -G "%GENERATOR%" ..
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target build_package_32
  - cmake --build . --config %CONFIGURATION% --target build_package_64

test_script:
  - cd ..
  - 'build\test\%CONFIGURATION%\%TESTEXE% -r vendor/AudioTestData -m build\main\%CONFIGURATION%\%MAINEXE%'
